apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-discovery-provider
  namespace: spire
data:
  oidc-discovery-provider.conf: |
    log_level = "INFO"
    domain = "example.com"
    acme {
        directory_url = "https://acme-staging-v02.api.letsencrypt.org/directory"
        cache_dir = "/run/spire"
        tos_accepted = true
        # TODO: replace it with a generic email?
        email = "marcos@scytale.io"
    }
    registration_api {
        socket_path = "/run/spire/sockets/registration.sock"
    }